spring.application.name=ExercicioSqs

spring.datasource.url=jdbc:mysql://awsmydbpleno.cu1e2e8emlw5.us-east-1.rds.amazonaws.com/testeAulaPlenoAws?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=xEOGhYKE21b2mPL6LKIv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.region=us-east-1